name: mibisualization
channels:
- conda-forge
- defaults
dependencies:
- pip=19.1.1
- python=3.7.3
- pip:
    - jupyterlab==1.2.6
    - Pillow==7.1.1
    - ipympl==0.5.6
    - matplotlib==2.2.3
    - numpy==1.16.0
    - pandas==0.23.4
    - scikit-image==0.16.2 
    - git+git://github.com/ionpath/mibitracker-client@v1.2.6
